### ISSUE TITLE
never get the result

### ISSUE THREAD

**Issue by imrshohel** [ahans30/Binoculars#6]
CPU: Cor i7 8th gen
GPU: 8GB
RAM: 40 GB

But when I ran the script, it ran into the local server but never finished its task. It continuously counts its time. Short to long text, I tried everything possible variation, but it never completed its analysis. Is there anything I need to adjust? Whatever the warning message, I already solved the PC configuration.

**Comment by ahans30** [comment]
This is because Binoculars runs two 7B sized language models which could take forever on CPUs. I'm sorry but running LMs on the CPU is not recommended and this behavior is expected. I would recommend you use resources like Kaggle or Colab Notebook to get GPU access if you're constrained on resources. 

You might wanna check out [this HuggingFace tutorial](https://huggingface.co/docs/transformers/en/perf_infer_cpu) to optimize LM inference on a CPU. Please feel free to send in PR for proper CPU support if you're able to optimize for it. 

Closing this issue since not much I can do here. Thanks for your interest in the project. :)
